import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createNativeTurnAdapter} from './native-turn-adapter.js';
const threadId='019d1234-1111-7111-8111-111111111111',turnId='019d1234-3333-7333-8333-333333333333';
const bound={threadId,sessionId:'019d1234-2222-7222-8222-222222222222',cwd:'/private/tmp/scoped',cliVersion:'0.145.0',model:'gpt-6.1',modelProvider:'openai'};
function server(mode='complete'){
 const program=`const readline=require('node:readline');let starts=0;const thread=${JSON.stringify({id:threadId,sessionId:bound.sessionId,cwd:bound.cwd,cliVersion:bound.cliVersion})};const emit=v=>process.stdout.write(JSON.stringify(v)+'\\n');readline.createInterface({input:process.stdin}).on('line',line=>{const r=JSON.parse(line);if(!r.id)return;let result={};if(r.method==='thread/read'){if(r.params.includeTurns!==false)process.exit(8);result={thread};}if(r.method==='thread/resume'){if(Object.keys(r.params).join()!=='threadId')process.exit(9);result={thread,cwd:thread.cwd,model:'gpt-6.1',modelProvider:'openai',approvalPolicy:'on-request',sandbox:{type:'readOnly',networkAccess:false}};}if(r.method==='turn/start'){if(++starts!==1)process.exit(10);if(r.params.sandboxPolicy.type!=='readOnly'||r.params.sandboxPolicy.networkAccess!==false)process.exit(11);${mode==='disconnect'?'process.exit(0);':'result={turn:{id:'+JSON.stringify(turnId)+',status:"inProgress",items:[],itemsView:"notLoaded",error:null,startedAt:null,completedAt:null,durationMs:null}};'}}emit({id:r.id,result});if(r.method==='turn/start'&&['complete','partial','stream','unloaded'].includes(${JSON.stringify(mode)})){emit({method:'turn/completed',params:{threadId:'foreign',turn:{id:${JSON.stringify(turnId)},status:'completed',itemsView:${JSON.stringify(mode==='unloaded'?'notLoaded':['partial','stream'].includes(mode)?'summary':'full')},error:null,startedAt:null,completedAt:null,durationMs:null,items:[]}}});if(['stream','unloaded'].includes(${JSON.stringify(mode)}))emit({method:'item/completed',params:{threadId:thread.id,turnId:${JSON.stringify(turnId)},completedAtMs:1,item:{type:'agentMessage',id:'m',text:'Bound reply',phase:'final_answer',memoryCitation:null}}});setTimeout(()=>emit({method:'turn/completed',params:{threadId:thread.id,turn:{id:${JSON.stringify(turnId)},status:'completed',itemsView:${JSON.stringify(mode==='unloaded'?'notLoaded':['partial','stream'].includes(mode)?'summary':'full')},error:null,startedAt:null,completedAt:null,durationMs:null,items:[{type:'agentMessage',id:'m',text:'Bound reply',phase:'final_answer',memoryCitation:null}]}}}),10);}if(r.method==='turn/interrupt'){if(r.params.threadId!==thread.id||r.params.turnId!==${JSON.stringify(turnId)})process.exit(12);setTimeout(()=>emit({method:'turn/completed',params:{threadId:thread.id,turn:{id:${JSON.stringify(turnId)},status:'interrupted',itemsView:${JSON.stringify(mode==='unloaded'?'notLoaded':['partial','stream'].includes(mode)?'summary':'full')},error:null,startedAt:null,completedAt:null,durationMs:null,items:[]}}}),10);}});`;
 return ()=>spawn(process.execPath,['-e',program],{stdio:['pipe','pipe','ignore']});
}
test('one persistent process resumes exact thread, commits issuance before start and sends correlated reply',async()=>{
 const journal=[],events=[];const adapter=await createNativeTurnAdapter(bound,{spawnServer:server(),timeoutMs:1000});
 try{const result=await adapter.run({effectId:threadId,issue:async()=>{events.push('issued');return{text:'Benign request',replyId:turnId};},persist:async row=>journal.push(row),report:async row=>events.push(row.state),reply:async row=>{events.push('reply');assert.equal(row.text,'Bound reply');return{replyId:turnId};}});assert.equal(result.state,'completed');assert.deepEqual(events,['issued','running','completed','reply']);assert.ok(journal.every(row=>!JSON.stringify(row).includes('Benign request')&&!JSON.stringify(row).includes('Bound reply')));}finally{adapter.close();}
});
test('lost turn/start response remains unknown and never creates a replacement turn',async()=>{const adapter=await createNativeTurnAdapter(bound,{spawnServer:server('disconnect'),timeoutMs:1000});let issued=0,replies=0;try{const result=await adapter.run({effectId:threadId,issue:async()=>{issued++;return{text:'Benign',replyId:turnId};},persist:async()=>{},report:async()=>{},reply:async()=>{replies++;}});assert.equal(result.state,'issued_unknown');assert.equal(issued,1);assert.equal(replies,0);await assert.rejects(adapter.run({effectId:threadId}),{code:'native_effect_already_issued'});}finally{adapter.close();}});
test('Stop interrupts exact admitted turn and waits for actual terminal notification',async()=>{const adapter=await createNativeTurnAdapter(bound,{spawnServer:server('wait'),timeoutMs:1000});const states=[];try{const running=adapter.run({effectId:threadId,issue:async()=>({text:'Benign',replyId:turnId}),persist:async()=>{},report:async row=>{states.push(row.state);if(row.state==='running')setTimeout(()=>adapter.stop(),5);},reply:async()=>assert.fail('interrupted turn must not fabricate reply')});assert.equal((await running).state,'stopped');assert.deepEqual(states,['running','stopped']);}finally{adapter.close();}});

test('lost authenticated reply receipt preserves completed turn without starting again',async()=>{const adapter=await createNativeTurnAdapter(bound,{spawnServer:server(),timeoutMs:1000});let replies=0;try{const result=await adapter.run({effectId:threadId,issue:async()=>({text:'Benign',replyId:turnId}),persist:async()=>{},report:async()=>{},reply:async()=>{replies++;throw new Error('untrusted transport detail');}});assert.deepEqual(result,{state:'completed',turnId,replyState:'unknown'});assert.equal(replies,1);await assert.rejects(adapter.run({effectId:threadId}),{code:'native_effect_already_issued'});}finally{adapter.close();}});

test('wait timeout retains original known turn, blocks another effect, and Stop targets it',async()=>{const adapter=await createNativeTurnAdapter(bound,{spawnServer:server('wait'),timeoutMs:100});try{const result=await adapter.run({effectId:threadId,issue:async()=>({text:'Benign',replyId:turnId}),persist:async()=>{},report:async()=>{},reply:async()=>assert.fail('no terminal reply')});assert.equal(result.state,'issued_unknown');await assert.rejects(adapter.run({effectId:turnId}),{code:'native_effect_unresolved'});assert.deepEqual(await adapter.stop(),{state:'stop_requested'});}finally{adapter.close();}});

test('summary terminal items never manufacture a complete reply',async()=>{const adapter=await createNativeTurnAdapter(bound,{spawnServer:server('partial'),timeoutMs:1000});try{const result=await adapter.run({effectId:threadId,issue:async()=>({text:'Benign',replyId:turnId}),persist:async()=>{},report:async()=>{},reply:async()=>assert.fail('partial items cannot be sent as a reply')});assert.deepEqual(result,{state:'completed',turnId,replyState:'unknown'});}finally{adapter.close();}});

for(const boundary of ['issue','persist'])test(`Stop during ${boundary} prevents turn/start and retains disclosure fence`,async()=>{let starts=0;const adapter=await createNativeTurnAdapter(bound,{spawnServer:()=>{const child=server('wait')();const write=child.stdin.write.bind(child.stdin);child.stdin.write=value=>{if(JSON.parse(value).method==='turn/start')starts++;return write(value);};return child;},timeoutMs:1000});try{const result=await adapter.run({effectId:threadId,issue:async()=>{if(boundary==='issue')await adapter.stop();return{text:'Benign',replyId:turnId};},persist:async row=>{if(boundary==='persist'&&row.state==='issued_unknown')await adapter.stop();},report:async()=>{},reply:async()=>assert.fail('no reply')});assert.deepEqual(result,{state:'issued_unknown'});assert.equal(starts,0);await assert.rejects(adapter.run({effectId:turnId}),{code:'native_effect_unresolved'});}finally{adapter.close();}});
for(const failure of ['persist','report'])test(`in-flight admission Stop survives ${failure} running callback failure`,async()=>{let interrupts=0,adapter;adapter=await createNativeTurnAdapter(bound,{spawnServer:()=>{const child=server('wait')();const write=child.stdin.write.bind(child.stdin);child.stdin.write=value=>{const method=JSON.parse(value).method;if(method==='turn/start')void adapter.stop();if(method==='turn/interrupt')interrupts++;return write(value);};return child;},timeoutMs:1000});try{const result=await adapter.run({effectId:threadId,issue:async()=>({text:'Benign',replyId:turnId}),persist:async row=>{if(failure==='persist'&&row.state==='running')throw new Error('private');},report:async row=>{if(failure==='report'&&row.state==='running')throw new Error('private');},reply:async()=>assert.fail('no reply')});assert.equal(result.state,'issued_unknown');assert.equal(interrupts,1);}finally{adapter.close();}});
for(const mode of ['stream','unloaded'])test(`exact completed final-answer item supplies reply for ${mode} terminal projection`,async()=>{const adapter=await createNativeTurnAdapter(bound,{spawnServer:server(mode),timeoutMs:1000});let replies=0;try{const result=await adapter.run({effectId:threadId,issue:async()=>({text:'Benign',replyId:turnId}),persist:async()=>{},report:async()=>{},reply:async row=>{replies++;assert.equal(row.text,'Bound reply');return{replyId:turnId};}});assert.equal(result.state,'completed');assert.equal(replies,1);}finally{adapter.close();}});

test('restart reconciliation interrupts only the original bound turn without starting',async()=>{const adapter=await createNativeTurnAdapter(bound,{spawnServer:server('wait'),timeoutMs:1000});try{await assert.rejects(adapter.reconcileStop({effectId:threadId,threadId:turnId,turnId}),{code:'native_scope_invalid'});assert.deepEqual(await adapter.reconcileStop({effectId:threadId,threadId,turnId}),{state:'stop_requested'});await assert.rejects(adapter.run({effectId:turnId}),{code:'native_effect_unresolved'});}finally{adapter.close();}});
