import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { checkpointReady, writeCheckpoint, readCheckpoint } from './tandem-checkpoint.js';
import { tandemNamespace } from './tandem-state.js';
const identity = { accountId: 'a', orgId: 'o', repoId: 'r', worktreeId: 'w', attemptId: 't' };
function sample() { return { schemaVersion: 1, namespace: tandemNamespace(identity), actionId: 'action', attemptId: 't', generation: 1, contractVersion: 1, baseSha: 'a'.repeat(40), headSha: 'b'.repeat(40), dirty: [], untracked: [], decisions: [], commands: [], nextSteps: [], unresolvedRisks: [], clean: true, scopeViolations: [], ownershipVerified: true }; }
test('unverified offline work is never review ready', () => { assert.equal(checkpointReady({ clean: true, scopeViolations: [], ownershipVerified: false }), false); assert.equal(checkpointReady({ clean: false, scopeViolations: [], ownershipVerified: true }), false); assert.equal(checkpointReady({ clean: true, scopeViolations: [], ownershipVerified: true }), true); });
test('checkpoint exact schema scrubs secrets and invalid/oversize preserves prior', async () => { const options = { baseDir: mkdtempSync(join(tmpdir(), 'checkpoint-')) }; const value = sample(); value.decisions = ['Authorization: Bearer abcdefghijklmnop']; await writeCheckpoint(identity, value, options); assert.match(readCheckpoint(identity, options).decisions[0], /redacted/); const path = join(options.baseDir, 'tandem/v2', tandemNamespace(identity), 'checkpoint.json'); const prior = readFileSync(path); await assert.rejects(writeCheckpoint(identity, { ...sample(), source: 'raw' }, options)); await assert.rejects(writeCheckpoint(identity, { ...sample(), decisions: ['x'.repeat(130000)] }, options)); assert.deepEqual(readFileSync(path), prior); });
test('checkpoint command assignments are scrubbed on disk and invalid writes preserve prior',async()=>{const options={baseDir:mkdtempSync(join(tmpdir(),'checkpoint-command-'))};const value=sample();value.commands=[{command:'tool password=swordfish secret=hidden api_key=private access-token=token',exitStatus:0,time:new Date().toISOString(),revision:value.headSha}];await writeCheckpoint(identity,value,options);const path=join(options.baseDir,'tandem/v2',tandemNamespace(identity),'checkpoint.json');const prior=readFileSync(path);for(const secret of ['swordfish','hidden','private','token'])assert.equal(prior.toString().includes('='+secret),false);await assert.rejects(writeCheckpoint(identity,{...value,commands:[{...value.commands[0],exitStatus:'invalid'}]},options));assert.deepEqual(readFileSync(path),prior);});
